# Generated by Django 5.2.3 on 2025-06-30 10:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('offense', models.CharField(max_length=100, verbose_name='Offense')),
                ('defense', models.TextField(blank=True, verbose_name='Defense')),
                ('decision', models.TextField(verbose_name='Decision')),
                ('penalty', models.CharField(blank=True, max_length=100, verbose_name='Penalty')),
                ('is_guilty', models.BooleanField(default=True, verbose_name='Is Guilty')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('attendance', models.ManyToManyField(blank=True, related_name='attended_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Attendance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
            },
        ),
    ]
