# Generated by Django 5.2.3 on 2025-06-24 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offense', models.CharField(max_length=100)),
                ('defense', models.TextField(blank=True)),
                ('decision', models.TextField()),
                ('penalty', models.CharField(blank=True, max_length=100)),
                ('is_guilty', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', models.ManyToManyField(blank=True, related_name='attended_disciplines', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
