# Generated by Django 5.2.3 on 2025-06-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sergeant_at_arms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='is_guilty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='penalty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
