# Generated by Django 5.2.3 on 2025-06-30 10:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('title', models.IntegerField(choices=[(10, 'Supporter'), (20, 'Hanground'), (30, 'Prospect'), (40, 'Member'), (41, 'President'), (42, 'Vice President'), (43, 'Sergent at Arms'), (44, 'Secretary'), (45, 'Treasurer'), (46, 'Road Captain'), (47, 'Tailgunner'), (48, 'Security'), (49, 'Mechanic'), (50, 'Frozen'), (60, 'Left'), (61, 'Out'), (62, 'No Contact'), (63, 'Out Bad'), (70, 'Deceased'), (71, 'Life Time Member')], default=20, verbose_name='Title')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Medical Conditions')),
                ('medications', models.TextField(blank=True, verbose_name='Medications')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=20, verbose_name='Blood Type')),
                ('driving_license_type', models.CharField(choices=[('none', 'None'), ('B', 'B'), ('A', 'A'), ('A2', 'A2'), ('A1', 'A1'), ('M', 'M')], default='none', max_length=5, verbose_name='License')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to=settings.AUTH_USER_MODEL, verbose_name='Sponsor')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=5, verbose_name='Type')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Format: +905555555555', max_length=128, region=None, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('what3words', models.CharField(blank=True, max_length=30, verbose_name='What3Words')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('meeting', 'Meeting'), ('ride', 'Ride'), ('party', 'Party'), ('other', 'Other')], max_length=10, verbose_name='Type')),
                ('name', models.CharField(default='Weekly Meeting', max_length=50, verbose_name='Name')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time')),
                ('location', models.CharField(default='Club House', max_length=50, verbose_name='Location')),
                ('agenda', models.TextField(blank=True, verbose_name='Agenda')),
                ('decisions', models.TextField(blank=True, verbose_name='Decisions')),
                ('training_note', models.TextField(blank=True, verbose_name='Training Note')),
                ('has_ride', models.BooleanField(default=False, verbose_name='Has Ride')),
                ('destination', models.CharField(blank=True, max_length=50, verbose_name='Destination')),
                ('ride_note', models.TextField(blank=True, verbose_name='Ride Note')),
                ('attendance', models.ManyToManyField(blank=True, related_name='attended_events', to=settings.AUTH_USER_MODEL, verbose_name='Attendance')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('brand', models.CharField(max_length=20, verbose_name='Brand')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)], verbose_name='Year')),
                ('plate', models.CharField(help_text='Format: 06ABC123', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Turkish license plate. (Ex: 06ABC123)', regex='^[0-9]{2}[A-Z]{1,3}[0-9]{2,4}$')], verbose_name='Plate')),
                ('engine_capacity', models.IntegerField(verbose_name='Engine Capacity')),
                ('last_maintenance_date', models.DateField(verbose_name='Last Maintenance Date')),
                ('inspection_expiry_date', models.DateField(verbose_name='Inspection Expiry Date')),
                ('insurance_expiry_date', models.DateField(verbose_name='Insurance Expiry Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Format: +905555555555', max_length=128, region=None, verbose_name='Phone')),
                ('relationship', models.CharField(max_length=20, verbose_name='Relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'unique_together': {('user', 'phone')},
            },
        ),
    ]
