# Generated by Django 5.2.3 on 2025-06-17 14:50

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Format: +905555555555', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=5),
        ),
        migrations.AlterField(
            model_name='contact',
            name='what3words',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Format: +905555555555', max_length=128, region=None),
        ),
    ]
