# Generated by Django 5.2.3 on 2025-06-27 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("secretary", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emergencycontact",
            unique_together={("user", "phone")},
        ),
    ]
