# Generated by Django 5.2.3 on 2025-06-18 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0002_alter_contact_address_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to=settings.AUTH_USER_MODEL),
        ),
    ]
