# Generated by Django 5.2.3 on 2025-06-18 08:41

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0003_user_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(help_text='Format: 06ABC123', max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid Turkish license plate. (Ex: 06ABC123)', regex='^[0-9]{2}[A-Z]{1,3}[0-9]{2,4}$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('meeting', 'Meeting'), ('ride', 'Ride'), ('party', 'Party'), ('other', 'Other')], max_length=10)),
                ('name', models.CharField(default='Weekly Meeting', max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default='Club House', max_length=50)),
                ('charter', models.IntegerField(choices=[(6, 'Ankara'), (26, 'Eskişehir')], default=6)),
                ('agenda', models.TextField(blank=True)),
                ('decisions', models.TextField(blank=True)),
                ('training_note', models.TextField(blank=True)),
                ('has_ride', models.BooleanField(default=False)),
                ('destination', models.CharField(blank=True, max_length=50)),
                ('ride_note', models.TextField(blank=True)),
                ('attendance', models.ManyToManyField(blank=True, related_name='attended_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
