"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ymqn1gorss^o-77z()4z$*jxj8k=v7o75kp1bhdd+30g9teai!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "phonenumber_field",
    "secretary",
    "treasury",
    "sergeant_at_arms",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "tr-tr"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("tr", "Turkish"),
    ("en", "English"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "secretary.User"

LOGIN_REDIRECT_URL = "/"

HANGROUND_DUE_AMOUNT = 1000
PROSPECT_DUE_AMOUNT = 1500
MEMBER_DUE_AMOUNT = 2000

UNFOLD = {
    "SITE_TITLE": "Black Flag MC",
    "SITE_HEADER": "Black Flag MC",
    "SITE_SUBHEADER": _("Management System"),
    "SITE_DROPDOWN": None,
    "SITE_URL": "/",
    "SITE_ICON": None,
    "SITE_SYMBOL": "flag",
    "SITE_LOGO": None,
    "SITE_FAVICONS": [],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_LANGUAGES": True,
    "SHOW_BACK_BUTTON": True,
    "COLORS": {
        "base": {
            "50": "249, 250, 251",
            "100": "243, 244, 246",
            "200": "229, 231, 235",
            "300": "209, 213, 219",
            "400": "156, 163, 175",
            "500": "107, 114, 128",
            "600": "75, 85, 99",
            "700": "55, 65, 81",
            "800": "31, 41, 55",
            "900": "17, 24, 39",
            "950": "3, 7, 18",
        },
        "primary": {
            50: "var(--color-base-50)",
            100: "var(--color-base-100)",
            200: "var(--color-base-200)",
            300: "var(--color-base-300)",
            400: "var(--color-base-400)",
            500: "var(--color-base-500)",
            600: "var(--color-base-600)",
            700: "var(--color-base-700)",
            800: "var(--color-base-800)",
            900: "var(--color-base-900)",
            950: "var(--color-base-950)",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",  # text-base-500
            "subtle-dark": "var(--color-base-400)",  # text-base-400
            "default-light": "var(--color-base-600)",  # text-base-600
            "default-dark": "var(--color-base-300)",  # text-base-300
            "important-light": "var(--color-base-900)",  # text-base-900
            "important-dark": "var(--color-base-100)",  # text-base-100
        },
    },
    "DASHBOARD_CALLBACK": "core.callbacks.dashboard.callback",
    "ENVIRONMENT": "core.callbacks.environment.callback",
    "ENVIRONMENT_TITLE_PREFIX": None,
    "STYLES": [],
    "SCRIPTS": [],
    "ACCOUNT": {
        "navigation": [
            # {
            #     "title": "title",
            #     "link": "link",
            # },
        ],
    },
    "LANGUAGES": {
        "action": None,
        "navigation": [],
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Navigation"),
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    }
                ],
            },
            {
                "title": _("Secretary"),
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "sports_motorsports",
                        "link": reverse_lazy("admin:secretary_user_changelist"),
                    },
                    {
                        "title": _("Events"),
                        "icon": "event",
                        "link": reverse_lazy("admin:secretary_event_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "secretary.view_event"
                        ),
                    },
                    {
                        "title": _("Contacts"),
                        "icon": "home",
                        "link": reverse_lazy("admin:secretary_contact_changelist"),
                    },
                    {
                        "title": _("Emergency Contacts"),
                        "icon": "emergency",
                        "link": reverse_lazy(
                            "admin:secretary_emergencycontact_changelist"
                        ),
                    },
                    {
                        "title": _("Vehicles"),
                        "icon": "two_wheeler",
                        "link": reverse_lazy("admin:secretary_vehicle_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "lock_person",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": _("Treasury"),
                "items": [
                    {
                        "title": _("Statements"),
                        "icon": "swap_vert",
                        "link": reverse_lazy("admin:treasury_statement_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "treasury.view_statement"
                        ),
                    },
                    {
                        "title": _("Dues"),
                        "icon": "face_down",
                        "link": reverse_lazy("admin:treasury_dues_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "treasury.view_dues"
                        ),
                        "badge": "core.callbacks.badges.dues_callback",
                    },
                    {
                        "title": _("Periods"),
                        "icon": "calendar_month",
                        "link": reverse_lazy("admin:treasury_period_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "treasury.view_period"
                        ),
                    },
                    {
                        "title": _("Inventories"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:treasury_inventory_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "treasury.view_inventory"
                        ),
                    },
                    {
                        "title": _("Inventory Items"),
                        "icon": "list",
                        "link": reverse_lazy("admin:treasury_inventoryitem_changelist"),
                        "permission": lambda request: request.user.has_perm(
                            "treasury.view_inventoryitem"
                        ),
                    },
                ],
            },
            {
                "title": _("Sergeant at Arms"),
                "items": [
                    {
                        "title": _("Penalties"),
                        "icon": "gavel",
                        "link": reverse_lazy(
                            "admin:sergeant_at_arms_discipline_changelist"
                        ),
                        "permission": lambda request: request.user.has_perm(
                            "sergeant_at_arms.view_discipline"
                        ),
                    },
                ],
            },
        ],
    },
    "TABS": [],
    "LOGIN": {
        "image": lambda request: static("images/login-bg.webp"),
        "redirect_after": None,
    },
    "EXTENSIONS": {"modeltranslation": {"flags": {}}},
}
