# Generated by Django 5.2.3 on 2025-06-24 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_statement_remove_income_user_period_dues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='month',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='period',
            name='year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
